### ISSUE TITLE
[BUG] Stress bots keeps disconnecting after creation

### ISSUE THREAD

**Issue by cooljef77** [ShaneBeee/StressTestBots#1]
### What happened?

[18:41:58 INFO]: Xeiji_ issued server command: /stress create random
[18:41:58 INFO]: [StressTestBots] Bot 'ikenvy' created
[18:41:58 INFO]: [StressTestBots] Bot 'ikenvy' disconnected
[18:42:01 INFO]: Xeiji_ issued server command: /stress create random
[18:42:01 INFO]: [StressTestBots] Bot 'Sonia' created
[18:42:01 INFO]: [StressTestBots] Bot 'Sonia' disconnected
[18:44:38 INFO]: Xeiji_ issued server command: /stress create named Notch
[18:44:38 INFO]: [StressTestBots] Bot 'Notch' created
[18:44:38 INFO]: [StressTestBots] Bot 'Notch' disconnected

### Steps to reproduce

create a stress bot
the bot created message pop up
bot disconnect (can only be seen in console)

### Expected behavior

Bot should not be disconnecting

### StressTestBots Version

1.0.0

### Server Version

Paper 1.20.4 (Java 21)

**Comment by ShaneBeee** [comment]
When I create a random, it logs the bot into the server
```
> stress create random
[09:48:07 INFO]: [StressTestBots] Bot '6_MasterBarbara_' created
[09:48:07 INFO]: [StressTestBots] Created new bot '6_MasterBarbara_'
[09:48:08 INFO]: UUID of player 6_MasterBarbara_ is d6cc5de9-4001-3f22-a610-18f7b2f14404
[09:48:08 INFO]: [+] 6_MasterBarbara_
[09:48:08 INFO]: 6_MasterBarbara_[/127.0.0.1:64076] logged in with entity id 1 at ([world]69.5, 63.0, -4.5)
```

Your console is showing that they're not even logging in, is there anything on your server that is denying the bots to log in?

This could be a hosting issue, which host are you on?

**Comment by cooljef77** [comment]
> This could be a hosting issue, which host are you on?
A free server hosting called MagmaNode

**Comment by ShaneBeee** [comment]
I dont know that one, but if its something like Minehut, I know that Minehut doesn't allow StressTestBots to work sadly.
Its due to their Proxy setup blocking external logins outside of the proxy.

**Comment by cooljef77** [comment]
I actually used this plugin before in the same hosting, different server but same version (1.20.4 Note: This is the latest version of minecraft at that moment) in there i am able to spawn the stressbots, will try to re-open that server and let you know

**Comment by ShaneBeee** [comment]
hmm... Im not sure then. It seems to be that the server is blocking the login.

**Comment by cooljef77** [comment]
To be sure, to enable it properly, I just need to make my server on offline mode by changing the server.properties  `online-mode=false`

**Comment by ShaneBeee** [comment]
that is correct.
if your server is "online" the plugin won't even run.

But the fact that based on your log (check mine), the bot isn't even joining the server, which tells me something on your server is denying the bot

**Comment by cooljef77** [comment]
![image](https://github.com/ShaneBeee/StressTestBots/assets/110924898/05b93d39-6a18-4425-9db4-47d4fb9124ed)
By any chance, there's no conflicting plugin in here right?

Also upon restarting the server, and inputting the command, seems the args are not detected by the system as it's red but it's going through, what a weird, this is most likely a hosting issue ig
![image](https://github.com/ShaneBeee/StressTestBots/assets/110924898/92f1c2b5-8bc0-45e4-b932-e04018403b91)

**Comment by ShaneBeee** [comment]
can you ping me on skUnity (assuming you’re on that discord) in #plugin-help and we can try sort this out

**Comment by cooljef77** [comment]
The issue is that the version that the stress bot is using is up to date (1.20.6) and if you're using older version of minecraft, the stress bot can't connect as of course, It's acting like a player (Resolved by installing ViaVersion) Thank you so much shane for the help!
